all:
  vars:
    ansible_user: ubuntu
    ansible_become: true
    ansible_ssh_private_key_file: /root/.ssh/id_rsa
  hosts:
    control-01:
      ansible_host: 192.168.1.127 # control-01
      ip: 192.168.1.127 # control-01
      access_ip: 192.168.1.127 # control-01
    worker-01:
      ansible_host: 192.168.1.129 # worker-01
      ip: 192.168.1.129 # worker-01
      access_ip: 192.168.1.129 # worker-01
    worker-02:
      ansible_host: 192.168.1.128 # worker-02
      ip: 192.168.1.128 # worker-02
      access_ip: 192.168.1.128 # worker-02
    worker-03:
      ansible_host: 192.168.1.126 # worker-03
      ip: 192.168.1.126 # worker-03
      access_ip: 192.168.1.126 # worker-03
  children:
    kube_control_plane:
      hosts:
        control-01:
    etcd:
      hosts:
        control-01:
    kube_node:
      hosts:
        worker-01:
        worker-02:
        worker-03:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node: